<?xml version="1.0"?>
<package format="3">
  <name>aed_emergency_response</name>
  <version>0.2.0</version>
  <description>语音触发的 VBot 急救物资配送和现场指导模式。</description>
  <maintainer email="developer@example.com">聆灵 VBot 二次开发团队</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>function_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>speech_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
